# Generated by Django 4.1.7 on 2023-03-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Author Name",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[("excellent", 1), ("average", 0), ("bad", -1)],
                        default="average",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
            },
        ),
    ]
